name: release-drafter

on:
  workflow_call:
    inputs:
      config-path:
        description: Path to the release-drafter config file
        required: false
        default: .github/release-drafter.yml
        type: string
      config-repository:
        description: Repository that stores the shared release-drafter config
        required: false
        default: gofiber/.github
        type: string
      config-ref:
        description: Ref to use when fetching the shared config repository
        required: false
        default: main
        type: string
    secrets:
      release-token:
        description: Optional token with `contents:write` permission
        required: false

permissions:
  contents: write
  pull-requests: read

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch shared release-drafter config
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          repository: ${{ inputs.config-repository }}
          ref: ${{ inputs.config-ref }}
          path: shared-config

      - name: Run release-drafter
        uses: release-drafter/release-drafter@b1476f6e6eb133afa41ed8589daba6dc69b4d3f5 # v6.1.0
        with:
          config-name: shared-config/${{ inputs.config-path }}
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.release-token != '' && secrets.release-token || secrets.GITHUB_TOKEN }}
